language: node_js
node_js:
  - node
dist: bionic
sudo: required
branches:
  only:
   - master #github repo branch
before_script:
  - npm install -g @angular/cli
script:
  # add node environment variables here
  - ng build --aot --prod #--base-href https://myformheroku.herokuapp.com/
deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $HEROKU_KEY
  # local_dir: dist/myform
  app: stark-coast-48290
  on:
    branch: master #github repo branch

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always
    # template:
    #   - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    #   - "Change view : %{compare_url}"
    #   - "Build details : %{build_url}"
